### ISSUE TITLE
Support for Xiaomi Bluetooth Mesh Downlights?

### ISSUE THREAD

**Issue by borodamd** [hcoohb/hass-yeelightbt#10]
Is any way to add support for Mesh Mi Light?
I can scan their mac's by hcitool, but after adding to configuration.yaml they in unavailable state.
Thanks.

**Comment by hcoohb** [comment]
Hi,

I am not sure what this product is exactly,
but if you have a gateway, [https://github.com/AlexxIT/XiaomiGateway3#supported-bluetooth-mesh-devices](https://github.com/AlexxIT/XiaomiGateway3#supported-bluetooth-mesh-devices) might help

**Comment by borodamd** [comment]
> Hi,
> 
> I am not sure what this product is exactly,
> but if you have a gateway, https://github.com/AlexxIT/XiaomiGateway3#supported-bluetooth-mesh-devices might help

Hi. I was able to connect these lights through Xiaomi Gateway 3, but will be much better to use them without gateway, because work is not stable and with delays.

**Comment by hcoohb** [comment]
This product use a different protocol.

Closing for now
