### ISSUE TITLE
Possiblity rto use with an ESP32?

### ISSUE THREAD

**Issue by Calcu2006** [hcoohb/hass-yeelightbt#11]
Hi,
I use some Esp32 with Home assistant in order to find my mi band.
It will be possible somehow to use this component with esphome ?

**Comment by hcoohb** [comment]
Hi,

Possibly, but a component for the esp32 would need to be created.
I have never played with bt on the esp32, but I have one or 2 around, so I might try that some days...

**Comment by xekil** [comment]
Hello, anything new?
I also have an ESP32 and that interests me because for a few weeks Yeelight-BT does not work for me with BLE Monitor.
Thank you

**Comment by hcoohb** [comment]
With HA 2022.10 and the use of bluetooth-proxy on an esp32, you can now control the bedside yeelight bt.
Not a native port but I seems to work quite well.

Closing this issue for now then

**Comment by xekil** [comment]
Hello, link please ?

**Comment by hcoohb** [comment]
You need to have HA 2022.10 and flash bluetooth-proxy component on the
esp32:
https://www.home-assistant.io/blog/2022/10/05/release-202210/#active-bluetooth-everywhere
