### ISSUE TITLE
Hassio always lost connection in a few minutes/hours

### ISSUE THREAD

**Issue by robiecz** [hcoohb/hass-yeelightbt#13]
Hi,
I have the Candela light, always connected to power. It works with this integration well, but in random time hassio lost connection. Candela is still reported like connected, but nothing happens when I try turn it on. The switch automatically return back to off in a few seconds.
Any ideas?

**Comment by hcoohb** [comment]
Unfortunately, ble connections are still very not overly stable, or I should stay the bt stack available in python....
The stack used to access python (bluepy) is quite temperamental and I have noticed as well that sometimes, it goes banana and does not respond. Restarting HA should fix the issue.
I know it is worse when some other integration are trying to use bt at the same time...

Sorry, but I don't think there's anything we can do about it...
At some point HA was talking of unifying the access to bt stack, which would help, but not sure when.

**Comment by hcoohb** [comment]
Closing this issue for now.
