### ISSUE TITLE
Problem Status with Remote Home-Assistant

### ISSUE THREAD

**Issue by xekil** [hcoohb/hass-yeelightbt#14]
Hello,

Thank you very much for this component which allows me to use both yeelight_bt (XMCDT01YL) of my children with home assistant, however, I have a particular problem, my configuration is as follows:

- Hassos 5.12 Master instance, core v2021.2.3
- Hassos 5.12 Secondary instance, core v2021.2.3 with hass-yeelightbt component

I use [Remote Home-Assistant](https://github.com/custom-components/remote_homeassistant) which allows bluetooth to be deported to a secondary home assistant instance, my entities go back correctly but the state of my two yeelight_bt poses a problem on the master instance:

When I operate them from the master instance, the state changes from ON, the lamp lights up and immediately after the state goes back to OFF but the lamp stays on.

To turn it off I have to turn it ON again then OFF so that the lamp goes out.

From the secondary instance there is no this problem and everything works fine.

Is it the hass-yeelightbt component which is not fully compatible with the [Remote Home-Assistant](https://github.com/custom-components/remote_homeassistant) component?

I don't have an error in the logs and I correctly associated my yellight_bt.

thank you in advance for your help

**Comment by hcoohb** [comment]
Hi,

I have never used remote Home-assistant so I don't know how it handle the reading/writing of bt entities...
But the yeelight_bt lamp is actually very  picky in how it handles the bt connection, so due to that, when the light is turned on, we actually need to wait some time before trying to read the state to confirm the light is on.

So it could be that the remote home-assistant is not waiting for the real notification and goes back to off on the master... the question is though why shouldn't it pick up that the light is on after some time?
If you physically turn on the light, does it gets picked up by the secondary instance? and by the master instance?

**Comment by xekil** [comment]
Hi,

After a physical press, HA and HA remote update the status exactly at the same time after about 20 seconds.

Strangely, apart from this delay, everything works fine today, strange.

On the other hand, I have a lot of error of this type:

```
Logger: custom_components.yeelight_bt.yeelightbt
Source: custom_components/yeelight_bt/yeelightbt.py:264
Integration: Yeelight bluetooth (documentation, issues)
First occurred: 14:45:38 (1 occurrences)
Last logged: 14:45:38

Could not write to lamp: error<class 'bluepy.btle.BTLEException'>(Error from bluepy-helper (badparam))
```
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:493
First occurred: 14:45:34 (1 occurrences)
Last logged: 14:45:34

Update of light.yeelight_leo is taking over 10 seconds
```

```
Logger: custom_components.yeelight_bt.yeelightbt
Source: custom_components/yeelight_bt/yeelightbt.py:260
Integration: Yeelight bluetooth (documentation, issues)
First occurred: 14:45:24 (2 occurrences)
Last logged: 14:45:31

Could not write to lamp: error<class 'bluepy.btle.BTLEInternalError'>(Helper not started (did you call connect()?)), Retrying now...
Could not write to lamp: error<class 'bluepy.btle.BTLEException'>(No current connection), Retrying now...
```
```
Logger: custom_components.yeelight_bt.yeelightbt
Source: custom_components/yeelight_bt/yeelightbt.py:76
Integration: Yeelight bluetooth (documentation, issues)
First occurred: 14:44:49 (2 occurrences)
Last logged: 14:45:31

Could not connect to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Failed to connect to peripheral g4:52:31:ef:c3:f8, addr type: public)
```

I am using BLE Monitor in parallel with the same Bluetooth dongle, I cannot use two Bluetooth dongles on the same device (Hass.io). Is this the source of these errors?

**Comment by hcoohb** [comment]
All of those problem should be fully resolved with the new bluetooth integration and using bluetooth-proxy on esp32.

Closing for now but feel free to reopen if needed
