### ISSUE TITLE
Lights not anymore available

### ISSUE THREAD

**Issue by mfabiani53** [hcoohb/hass-yeelightbt#16]
Suddenly this morning all the Bluetooth yeelights went to unavailable mode without changing anything from my side except upgrade to the latest release from HACS.
Any hints?

**Comment by hcoohb** [comment]
Hi,

You might need to give a bit more details...
Is there any issues in the log? What is your system HAOS, hass container,...? Do you have only one entity using bt?
That latest release literally has no change to the code whatswhover, it is only to add a `version` setting string that will be required in some upcoming hass release..
A restart of HA did not help?
