### ISSUE TITLE
Config flow error

### ISSUE THREAD

**Issue by mouth4war** [hcoohb/hass-yeelightbt#18]
`Error occurred loading configuration flow for integration yeelight_bt: cannot import name 'Embedded' from 'construct' (/usr/local/lib/python3.9/site-packages/construct/__init__.py)`

**Comment by mouth4war** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:698

**Comment by hcoohb** [comment]
Hi,
I am curious about this error: this repo does not use the construct library at all...
Are you sure you have not installed the component from rytilahti repo?
Or was it installed before?

**Comment by mouth4war** [comment]
I uninstalled and reinstalled from HACS and now config flow works. Getting a permissions error despite changing docker container capabilities.
