### ISSUE TITLE
any plan support Yeelight Smart Dimmer Switch?

### ISSUE THREAD

**Issue by shensven** [hcoohb/hass-yeelightbt#2]
Hi bro,
any plan support [Yeelight Smart dimmer switch](https://www.yeelight.com/zh_CN/product/seesaw) and [Yeelight Remote Control](https://www.yeelight.com/zh_CN/product/kiwi)?
Yeelight Smart dimmer switch is a real awesome remote controller with BLE, No directly disconnection from Power.

**Comment by hcoohb** [comment]
Hi,
At this stage this project focuses on the yeelight bedside lamp and Candella as they have very similar bluetooth protocols.

Unfortunately I do not possess any of those devices and it will get pretty hard to try to support without being able to test. The had part is to reverse engineer the bluetooth protocols used by those devices.
Are you aware of any libraries that have already established the protocols?

**Comment by hcoohb** [comment]
Closing this issue as those devices will not be supported for the time being.
Thanks
