### ISSUE TITLE
[Feature] Adding more available entities

### ISSUE THREAD

**Issue by Dvalin21** [hcoohb/hass-yeelightbt#60]
### Light

Yeelight Bedside

### Yeelight Bt version

1.3.0

### Home-assistant installation type

Home Assistant Operating System (HAOS)

### Home-assistant version

2023.9

### Home-assistant bluetooth integration (2022.8+)

Yes

### Describe the issue

Not sure if this integration is still being supported, but I was hoping that more available entities would be made available for us.  Thanks

### Debugging procedure followed:

- [ ] 1- Ensure smartphone will not connect with lamp
- [ ] 2- The Yeelight_bt integration has been removed from HA.
- [ ] 3- HA has access to the bluetooth adapter (followed the installation steps if not on HAOS).
- [ ] 4- No other bluetooth integration are using something else than bleak library for bluetooth. If unsure, disable them.
- [ ] 5- The logging has been changed in HA to allow debugging of this component and bleak.
- [ ] 6- The light has been fully reset so that it is not paired with any device.
- [ ] 7- Restart HA
- [ ] 8- Reinstall the yeelight_bt integration and find the light through a scan.
- [ ] 9- Pairing the lamp succeeded

**Comment by hcoohb** [comment]
Hi,

What other entities are you referring to?
This integration only support the yeelight bedside bluetooth and to some degree the yeelight candela

**Comment by Dvalin21** [comment]
> Hi,
> 
> What other entities are you referring to? This integration only support the yeelight bedside bluetooth and to some degree the yeelight candela

Be honest with ya, I completely forget the idea I had in mind. Ill close this for now.
