### ISSUE TITLE
[Bug] failure after Home Assistant Update 2024.1

### ISSUE THREAD

**Issue by Dual-0** [hcoohb/hass-yeelightbt#62]
### Light

Yeelight Bedside

### Yeelight Bt version

v1.3.0

### Home-assistant installation type

Home Assistant Container (docker)

### Home-assistant version

2024.1

### Home-assistant bluetooth integration (2022.8+)

Yes

### Describe the issue

When adding the integration it shows:
`{"message":"Invalid handler specified"}`

### Debugging procedure followed:

- [ ] 1- Ensure smartphone will not connect with lamp
- [ ] 2- The Yeelight_bt integration has been removed from HA.
- [X] 3- HA has access to the bluetooth adapter (followed the installation steps if not on HAOS).
- [X] 4- No other bluetooth integration are using something else than bleak library for bluetooth. If unsure, disable them.
- [ ] 5- The logging has been changed in HA to allow debugging of this component and bleak.
- [ ] 6- The light has been fully reset so that it is not paired with any device.
- [X] 7- Restart HA
- [ ] 8- Reinstall the yeelight_bt integration and find the light through a scan.
- [ ] 9- Pairing the lamp succeeded

### Logs from the issue

Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 23:36:20 (2 occurrences)
Last logged: 23:46:56

Error occurred loading flow for integration yeelight_bt: cannot import name 'BluetoothScanningMode' from 'homeassistant.components.bluetooth.models' (/usr/src/homeassistant/homeassistant/components/bluetooth/models.py)

**Comment by xekil** [comment]
same error

**Comment by xekil** [comment]
Fix work, thank you

**Comment by golgothar** [comment]
Same error and debugging procedure doesnt work.
error  : 
Error occurred loading flow for integration yeelight_bt: cannot import name 'BluetoothScanningMode' from 'homeassistant.components.bluetooth.models' (/usr/src/homeassistant/homeassistant/components/bluetooth/models.py)

**Comment by Dvalin21** [comment]
Same error receiving the following

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by golgothar** [comment]
The code modification in the config flow file works.

**Comment by hcoohb** [comment]
It should be fixed in latest release.
Thanks for reporting and the PR!
