### ISSUE TITLE
Entity not available: light.xiaomi_candle

### ISSUE THREAD

**Issue by davisdmg** [hcoohb/hass-yeelightbt#8]
Hi!

I was able to follow the instructions on Hassio and everything worked like charm. The discovery found the candle after reseting it and I was able to control it.

However, after a while, I get that error and I have to shut down the candle to get it online again.

This is what I have in the logs:

`Logger: custom_components.yeelight_bt.yeelightbt
Source: custom_components/yeelight_bt/yeelightbt.py:260
Integration: Yeelight bluetooth (documentation, issues)
First occurred: 11:20:00 PM (1 occurrences)
Last logged: 11:20:00 PM

Could not write to lamp: error<class 'bluepy.btle.BTLEDisconnectError'>(Device disconnected), Retrying now...`

Am I doing something wrong?

**Comment by davisdmg** [comment]
Nevermind, I did everything again and now it doesnt loose the conection.

If you want any data from this device, just ping me and I will share with you!

**Comment by hcoohb** [comment]
The bt stack with bluepy is not an example of stability unfortunately...
I do have some lost connection from time to time, and it is worse if other integrations are trying to use bt as well...
Restarting HA helps.

I'll close the issue since you have fixed it but feel free to re-open if needed.
