### ISSUE TITLE
How to add permissions for network scan on Supervised HA docker installation?

### ISSUE THREAD

**Issue by Pansovi4** [hcoohb/hass-yeelightbt#9]
Hi, please help

https://community.home-assistant.io/t/how-to-add-capabilities-net-admin-net-raw-on-supervised-ha/241971?u=pansovi4

**Comment by hcoohb** [comment]
https://www.home-assistant.io/integrations/bluetooth/ explains the procedure to ensure the newer bluetooth integration can be configured.

closing for now
